name: education_app_flutter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  bloc: ^8.1.2
  chewie: ^1.7.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  file_picker: ^6.0.0
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.4
  iconly: ^1.0.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  lottie: ^2.7.0
  open_file: ^3.3.2
  path_provider: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.2
  url_launcher: ^6.1.14
  youtube_metadata: ^1.0.1
  video_thumbnail: ^0.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  bloc_test: ^9.1.4
  flutter_lints: ^2.0.0
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/vectors/
    - assets/images/
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
